// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x212A31), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_Panels_1 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_Panels_1);
lv_obj_set_width( ui_Container_Panels_1, 450);
lv_obj_set_height( ui_Container_Panels_1, 600);
lv_obj_set_align( ui_Container_Panels_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container_Panels_1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_Panels_1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container_Panels_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_Panels_1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_Panels_1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Container_Panels_1);
lv_obj_set_width( ui_Panel5, 199);
lv_obj_set_height( ui_Panel5, 261);
lv_obj_set_x( ui_Panel5, -39 );
lv_obj_set_y( ui_Panel5, -167 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel5, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x82C9D9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel16 = lv_obj_create(ui_Panel5);
lv_obj_set_width( ui_Panel16, 200);
lv_obj_set_height( ui_Panel16, 200);
lv_obj_set_x( ui_Panel16, 72 );
lv_obj_set_y( ui_Panel16, -18 );
lv_obj_set_align( ui_Panel16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel16, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Container_Panels_1);
lv_obj_set_width( ui_Panel4, 199);
lv_obj_set_height( ui_Panel4, 261);
lv_obj_set_x( ui_Panel4, -39 );
lv_obj_set_y( ui_Panel4, -167 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel4, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel17 = lv_obj_create(ui_Panel4);
lv_obj_set_width( ui_Panel17, 300);
lv_obj_set_height( ui_Panel17, 300);
lv_obj_set_x( ui_Panel17, 103 );
lv_obj_set_y( ui_Panel17, -65 );
lv_obj_set_align( ui_Panel17, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel17, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel17, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Container_Panels_1);
lv_obj_set_width( ui_Panel6, 199);
lv_obj_set_height( ui_Panel6, 261);
lv_obj_set_x( ui_Panel6, -39 );
lv_obj_set_y( ui_Panel6, -167 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel6, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xF1AE88), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel18 = lv_obj_create(ui_Panel6);
lv_obj_set_width( ui_Panel18, 150);
lv_obj_set_height( ui_Panel18, 150);
lv_obj_set_x( ui_Panel18, 13 );
lv_obj_set_y( ui_Panel18, -72 );
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel18, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_Container_Panels_1);
lv_obj_set_width( ui_Panel7, 199);
lv_obj_set_height( ui_Panel7, 261);
lv_obj_set_x( ui_Panel7, -39 );
lv_obj_set_y( ui_Panel7, -167 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel7, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xD3C9A3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_washing = lv_img_create(ui_Screen2);
lv_img_set_src(ui_icon_washing, &ui_img_img_icon_washer_png);
lv_obj_set_width( ui_icon_washing, LV_SIZE_CONTENT);  /// 174
lv_obj_set_height( ui_icon_washing, LV_SIZE_CONTENT);   /// 174
lv_obj_set_x( ui_icon_washing, -59 );
lv_obj_set_y( ui_icon_washing, 72 );
lv_obj_set_align( ui_icon_washing, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_washing, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_washing, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_washing_off = lv_img_create(ui_icon_washing);
lv_img_set_src(ui_Icon_washing_off, &ui_img_img_icon_washer_off_png);
lv_obj_set_width( ui_Icon_washing_off, LV_SIZE_CONTENT);  /// 81
lv_obj_set_height( ui_Icon_washing_off, LV_SIZE_CONTENT);   /// 98
lv_obj_set_x( ui_Icon_washing_off, 21 );
lv_obj_set_y( ui_Icon_washing_off, -25 );
lv_obj_set_align( ui_Icon_washing_off, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_washing_off, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_washing_off, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_cleaner = lv_img_create(ui_Screen2);
lv_img_set_src(ui_icon_cleaner, &ui_img_img_icon_cleaner_png);
lv_obj_set_width( ui_icon_cleaner, LV_SIZE_CONTENT);  /// 192
lv_obj_set_height( ui_icon_cleaner, LV_SIZE_CONTENT);   /// 170
lv_obj_set_x( ui_icon_cleaner, -58 );
lv_obj_set_y( ui_icon_cleaner, -225 );
lv_obj_set_align( ui_icon_cleaner, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_cleaner, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_cleaner, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_cleaner_off = lv_img_create(ui_icon_cleaner);
lv_img_set_src(ui_Icon_cleaner_off, &ui_img_img_icon_cleaner_off_png);
lv_obj_set_width( ui_Icon_cleaner_off, LV_SIZE_CONTENT);  /// 192
lv_obj_set_height( ui_Icon_cleaner_off, LV_SIZE_CONTENT);   /// 170
lv_obj_set_x( ui_Icon_cleaner_off, 0 );
lv_obj_set_y( ui_Icon_cleaner_off, -26 );
lv_obj_set_align( ui_Icon_cleaner_off, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_cleaner_off, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_cleaner_off, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_pagination_1 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_pagination_1);
lv_obj_set_width( ui_Container_pagination_1, 200);
lv_obj_set_height( ui_Container_pagination_1, 23);
lv_obj_set_x( ui_Container_pagination_1, 0 );
lv_obj_set_y( ui_Container_pagination_1, -10 );
lv_obj_set_align( ui_Container_pagination_1, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Container_pagination_1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_pagination_1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Container_pagination_1, LV_OBJ_FLAG_FLOATING );   /// Flags
lv_obj_clear_flag( ui_Container_pagination_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_pagination_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_pagination_1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_Container_pagination_1);
lv_obj_set_width( ui_Panel10, 10);
lv_obj_set_height( ui_Panel10, 10);
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_Container_pagination_1);
lv_obj_set_width( ui_Panel12, 10);
lv_obj_set_height( ui_Panel12, 10);
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_cleaner = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_cleaner);
lv_obj_set_width( ui_Container_cleaner, 199);
lv_obj_set_height( ui_Container_cleaner, 257);
lv_obj_set_x( ui_Container_cleaner, -108 );
lv_obj_set_y( ui_Container_cleaner, -139 );
lv_obj_set_align( ui_Container_cleaner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_cleaner, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Roller2 = lv_roller_create(ui_Container_cleaner);
lv_roller_set_options( ui_Roller2, "Auto\nSpot\nEdge", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_Roller2, 110);
lv_obj_set_height( ui_Roller2, 45);
lv_obj_set_x( ui_Roller2, 0 );
lv_obj_set_y( ui_Roller2, -5 );
lv_obj_set_align( ui_Roller2, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller2, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Roller2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller2, &ui_font_Kanit25, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Roller2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller2, 100, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label_batt = lv_label_create(ui_Container_cleaner);
lv_obj_set_width( ui_Label_batt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_batt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_batt, 9 );
lv_obj_set_y( ui_Label_batt, 157 );
lv_label_set_text(ui_Label_batt,"Battery");
lv_obj_set_style_text_color(ui_Label_batt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_batt, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_batt, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_Container_cleaner);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 104);
lv_obj_set_height( ui_Container5, 49);
lv_obj_set_x( ui_Container5, 47 );
lv_obj_set_y( ui_Container5, 41 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_battery = lv_label_create(ui_Container5);
lv_obj_set_height( ui_Label_battery, 40);
lv_obj_set_width( ui_Label_battery, LV_SIZE_CONTENT);  /// 56
lv_obj_set_x( ui_Label_battery, -7 );
lv_obj_set_y( ui_Label_battery, 0 );
lv_label_set_text(ui_Label_battery,"50");
lv_obj_set_style_text_color(ui_Label_battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_battery, &ui_font_Kanit50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item8 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label_item8, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_Label_item8, LV_SIZE_CONTENT);   /// 40
lv_label_set_text(ui_Label_item8,"%");
lv_obj_set_style_text_color(ui_Label_item8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item8, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider_vacuum_batt = lv_slider_create(ui_Container_cleaner);
lv_slider_set_value( ui_Slider_vacuum_batt, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_vacuum_batt)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_vacuum_batt, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_vacuum_batt, 185);
lv_obj_set_height( ui_Slider_vacuum_batt, 7);
lv_obj_set_x( ui_Slider_vacuum_batt, 0 );
lv_obj_set_y( ui_Slider_vacuum_batt, 61 );
lv_obj_set_align( ui_Slider_vacuum_batt, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Slider_vacuum_batt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Slider_vacuum_batt, lv_color_hex(0x749CA4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_vacuum_batt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_vacuum_batt, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_vacuum_batt, lv_color_hex(0x0795BE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_vacuum_batt, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Slider_vacuum_batt, LV_GRAD_DIR_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider_vacuum_batt, lv_color_hex(0x0795BE), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_vacuum_batt, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Slider_vacuum_batt, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Slider_vacuum_batt, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Slider_vacuum_batt, 30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Slider_vacuum_batt, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label_Vacuum = lv_label_create(ui_Container_cleaner);
lv_obj_set_width( ui_Label_Vacuum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Vacuum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Vacuum, 5 );
lv_obj_set_y( ui_Label_Vacuum, 79 );
lv_label_set_text(ui_Label_Vacuum,"Vacuum\nCleaner");
lv_obj_set_style_text_color(ui_Label_Vacuum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Vacuum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_Vacuum, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_Vacuum, -5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Vacuum, &ui_font_Kanit35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch_vacuum = lv_switch_create(ui_Container_cleaner);
lv_obj_set_width( ui_Switch_vacuum, 70);
lv_obj_set_height( ui_Switch_vacuum, 70);
lv_obj_set_x( ui_Switch_vacuum, -57 );
lv_obj_set_y( ui_Switch_vacuum, -89 );
lv_obj_set_align( ui_Switch_vacuum, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Switch_vacuum, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_vacuum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_vacuum, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Switch_vacuum, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_vacuum, lv_color_hex(0xACAEAC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_vacuum, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_vacuum, lv_color_hex(0x31BE08), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch_vacuum, 100, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_Switch_vacuum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_vacuum, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch_vacuum, &ui_img_636281941, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Switch_vacuum, lv_color_hex(0xAFAFAF), LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Switch_vacuum, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Switch_vacuum, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Switch_vacuum, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Switch_vacuum, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Switch_vacuum, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch_vacuum, &ui_img_636281941, LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_img_recolor(ui_Switch_vacuum, lv_color_hex(0x35BD0C), LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_recolor_opa(ui_Switch_vacuum, 255, LV_PART_KNOB| LV_STATE_CHECKED);

ui_Container_WM = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_WM);
lv_obj_set_width( ui_Container_WM, 201);
lv_obj_set_height( ui_Container_WM, 258);
lv_obj_set_x( ui_Container_WM, -108 );
lv_obj_set_y( ui_Container_WM, 137 );
lv_obj_set_align( ui_Container_WM, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_WM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_Container_WM);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 193);
lv_obj_set_height( ui_Container6, 108);
lv_obj_set_x( ui_Container6, 1 );
lv_obj_set_y( ui_Container6, 62 );
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Smart = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_Button_Smart, 92);
lv_obj_set_height( ui_Button_Smart, 50);
lv_obj_set_x( ui_Button_Smart, -44 );
lv_obj_set_y( ui_Button_Smart, 30 );
lv_obj_set_align( ui_Button_Smart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Smart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Smart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Smart, lv_color_hex(0xE5875A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Smart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button_Smart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button_Smart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Button_Smart, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Smart, lv_color_hex(0xFF732F), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_Smart, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Button_Smart, lv_color_hex(0xDA662B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Button_Smart, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Button_Smart, 2, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_font(ui_Button_Smart, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_Button_Smart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Button_Smart, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label_WM1 = lv_label_create(ui_Button_Smart);
lv_obj_set_width( ui_Label_WM1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_WM1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_WM1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_WM1,"Smart");

ui_Button_Quick = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_Button_Quick, 92);
lv_obj_set_height( ui_Button_Quick, 50);
lv_obj_set_x( ui_Button_Quick, 55 );
lv_obj_set_y( ui_Button_Quick, 31 );
lv_obj_set_align( ui_Button_Quick, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Quick, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Quick, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Quick, lv_color_hex(0xE5875A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Quick, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button_Quick, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button_Quick, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Button_Quick, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Quick, lv_color_hex(0xFF732F), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_Quick, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Button_Quick, lv_color_hex(0xDA662B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Button_Quick, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Button_Quick, 2, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_font(ui_Button_Quick, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_Button_Quick, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Button_Quick, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label_WM2 = lv_label_create(ui_Button_Quick);
lv_obj_set_width( ui_Label_WM2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_WM2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_WM2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_WM2,"Quick");

ui_Button_Linen = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_Button_Linen, 92);
lv_obj_set_height( ui_Button_Linen, 50);
lv_obj_set_x( ui_Button_Linen, 55 );
lv_obj_set_y( ui_Button_Linen, 31 );
lv_obj_set_align( ui_Button_Linen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Linen, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Linen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Linen, lv_color_hex(0xE5875A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Linen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button_Linen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button_Linen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Button_Linen, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Linen, lv_color_hex(0xFF732F), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_Linen, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Button_Linen, lv_color_hex(0xDA662B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Button_Linen, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Button_Linen, 2, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_font(ui_Button_Linen, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_Button_Linen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Button_Linen, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label_WM3 = lv_label_create(ui_Button_Linen);
lv_obj_set_width( ui_Label_WM3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_WM3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_WM3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_WM3,"Linen");

ui_Button_Saver = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_Button_Saver, 92);
lv_obj_set_height( ui_Button_Saver, 50);
lv_obj_set_x( ui_Button_Saver, 55 );
lv_obj_set_y( ui_Button_Saver, 31 );
lv_obj_set_align( ui_Button_Saver, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Saver, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Saver, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Saver, lv_color_hex(0xE5875A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Saver, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button_Saver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button_Saver, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Button_Saver, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Saver, lv_color_hex(0xFF732F), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_Saver, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Button_Saver, lv_color_hex(0xDA662B), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Button_Saver, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Button_Saver, 2, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_font(ui_Button_Saver, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_Button_Saver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Button_Saver, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label_WM4 = lv_label_create(ui_Button_Saver);
lv_obj_set_width( ui_Label_WM4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_WM4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_WM4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_WM4,"Saver");

ui_Label_wm_timer = lv_label_create(ui_Container_WM);
lv_obj_set_width( ui_Label_wm_timer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_wm_timer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_wm_timer, 15 );
lv_obj_set_y( ui_Label_wm_timer, 96 );
lv_label_set_text(ui_Label_wm_timer,"00:00");
lv_obj_set_style_text_color(ui_Label_wm_timer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_wm_timer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_wm_timer, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_wm = lv_label_create(ui_Container_WM);
lv_obj_set_width( ui_Label_wm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_wm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_wm, 15 );
lv_obj_set_y( ui_Label_wm, 71 );
lv_label_set_text(ui_Label_wm,"ETR");
lv_obj_set_style_text_color(ui_Label_wm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_wm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_wm, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_SP = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_SP);
lv_obj_set_width( ui_Container_SP, 201);
lv_obj_set_height( ui_Container_SP, 258);
lv_obj_set_x( ui_Container_SP, 106 );
lv_obj_set_y( ui_Container_SP, -137 );
lv_obj_set_align( ui_Container_SP, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_SP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch_SP = lv_switch_create(ui_Container_SP);
lv_obj_set_width( ui_Switch_SP, 80);
lv_obj_set_height( ui_Switch_SP, 80);
lv_obj_set_x( ui_Switch_SP, -49 );
lv_obj_set_y( ui_Switch_SP, 77 );
lv_obj_set_align( ui_Switch_SP, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Switch_SP, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_SP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_SP, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Switch_SP, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_SP, lv_color_hex(0xACAEAC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_SP, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_SP, lv_color_hex(0x31BE08), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch_SP, 100, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_Switch_SP, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_SP, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch_SP, &ui_img_636281941, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Switch_SP, lv_color_hex(0xAFAFAF), LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Switch_SP, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Switch_SP, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Switch_SP, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Switch_SP, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Switch_SP, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch_SP, &ui_img_636281941, LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_img_recolor(ui_Switch_SP, lv_color_hex(0x35BD0C), LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_recolor_opa(ui_Switch_SP, 255, LV_PART_KNOB| LV_STATE_CHECKED);

ui_Container7 = lv_obj_create(ui_Container_SP);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 116);
lv_obj_set_height( ui_Container7, 50);
lv_obj_set_x( ui_Container7, -28 );
lv_obj_set_y( ui_Container7, -93 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_watt = lv_label_create(ui_Container7);
lv_obj_set_height( ui_Label_watt, 40);
lv_obj_set_width( ui_Label_watt, LV_SIZE_CONTENT);  /// 56
lv_obj_set_x( ui_Label_watt, -7 );
lv_obj_set_y( ui_Label_watt, 0 );
lv_label_set_text(ui_Label_watt,"0");
lv_obj_set_style_text_color(ui_Label_watt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_watt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_watt, &ui_font_Kanit50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item11 = lv_label_create(ui_Container7);
lv_obj_set_width( ui_Label_item11, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_Label_item11, LV_SIZE_CONTENT);   /// 40
lv_label_set_text(ui_Label_item11,"W");
lv_obj_set_style_text_color(ui_Label_item11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item11, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item10 = lv_label_create(ui_Container_SP);
lv_obj_set_width( ui_Label_item10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_item10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_item10, 100 );
lv_obj_set_y( ui_Label_item10, 165 );
lv_label_set_text(ui_Label_item10,"Smart\nPlug");
lv_obj_set_style_text_color(ui_Label_item10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_item10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_item10, -3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item10, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_SP = lv_label_create(ui_Container_SP);
lv_obj_set_width( ui_Label_SP, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_SP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_SP, 99 );
lv_obj_set_y( ui_Label_SP, 218 );
lv_label_set_text(ui_Label_SP,"OFF");
lv_obj_set_style_text_color(ui_Label_SP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_SP, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_SP, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_EV = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_EV);
lv_obj_set_width( ui_Container_EV, 200);
lv_obj_set_height( ui_Container_EV, 263);
lv_obj_set_x( ui_Container_EV, 107 );
lv_obj_set_y( ui_Container_EV, 138 );
lv_obj_set_align( ui_Container_EV, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_EV, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container_EV, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar_ev = lv_bar_create(ui_Container_EV);
lv_bar_set_value(ui_Bar_ev,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar_ev, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar_ev, 199);
lv_obj_set_height( ui_Bar_ev, 262);
lv_obj_set_x( ui_Bar_ev, -2 );
lv_obj_set_y( ui_Bar_ev, -1 );
lv_obj_set_align( ui_Bar_ev, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_ev, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_ev, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_ev, lv_color_hex(0x55FB9D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_ev, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Panel19 = lv_obj_create(ui_Container_EV);
lv_obj_set_width( ui_Panel19, 200);
lv_obj_set_height( ui_Panel19, 200);
lv_obj_set_x( ui_Panel19, 27 );
lv_obj_set_y( ui_Panel19, 7 );
lv_obj_set_align( ui_Panel19, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel19, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel19, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel19, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_EV = lv_label_create(ui_Container_EV);
lv_obj_set_width( ui_Label_EV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_EV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_EV, 12 );
lv_obj_set_y( ui_Label_EV, 13 );
lv_label_set_text(ui_Label_EV,"EV Charger");
lv_obj_set_style_text_color(ui_Label_EV, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_EV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_EV, &ui_font_Kanit35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_Container_EV);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, 116);
lv_obj_set_height( ui_Container8, 50);
lv_obj_set_x( ui_Container8, -29 );
lv_obj_set_y( ui_Container8, -62 );
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container8,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_ev_battery = lv_label_create(ui_Container8);
lv_obj_set_height( ui_Label_ev_battery, 40);
lv_obj_set_width( ui_Label_ev_battery, LV_SIZE_CONTENT);  /// 56
lv_obj_set_x( ui_Label_ev_battery, -7 );
lv_obj_set_y( ui_Label_ev_battery, 0 );
lv_label_set_text(ui_Label_ev_battery,"50");
lv_obj_set_style_text_color(ui_Label_ev_battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_ev_battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_ev_battery, &ui_font_Kanit50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item12 = lv_label_create(ui_Container8);
lv_obj_set_width( ui_Label_item12, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_Label_item12, LV_SIZE_CONTENT);   /// 40
lv_label_set_text(ui_Label_item12,"%");
lv_obj_set_style_text_color(ui_Label_item12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item12, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_smart_plug = lv_img_create(ui_Screen2);
lv_img_set_src(ui_icon_smart_plug, &ui_img_img_icon_plug_png);
lv_obj_set_width( ui_icon_smart_plug, LV_SIZE_CONTENT);  /// 140
lv_obj_set_height( ui_icon_smart_plug, LV_SIZE_CONTENT);   /// 185
lv_obj_set_x( ui_icon_smart_plug, 155 );
lv_obj_set_y( ui_icon_smart_plug, -213 );
lv_obj_set_align( ui_icon_smart_plug, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_smart_plug, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_smart_plug, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_smart_plug_on = lv_img_create(ui_icon_smart_plug);
lv_img_set_src(ui_icon_smart_plug_on, &ui_img_img_icon_plug_on_png);
lv_obj_set_width( ui_icon_smart_plug_on, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_icon_smart_plug_on, LV_SIZE_CONTENT);   /// 56
lv_obj_set_x( ui_icon_smart_plug_on, 30 );
lv_obj_set_y( ui_icon_smart_plug_on, -14 );
lv_obj_set_align( ui_icon_smart_plug_on, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_smart_plug_on, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_smart_plug_on, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_car = lv_img_create(ui_Screen2);
lv_img_set_src(ui_icon_car, &ui_img_img_icon_car_png);
lv_obj_set_width( ui_icon_car, LV_SIZE_CONTENT);  /// 69
lv_obj_set_height( ui_icon_car, LV_SIZE_CONTENT);   /// 148
lv_obj_set_x( ui_icon_car, 92 );
lv_obj_set_y( ui_icon_car, 150 );
lv_obj_set_align( ui_icon_car, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_car, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_car, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_car_on = lv_img_create(ui_Screen2);
lv_img_set_src(ui_icon_car_on, &ui_img_img_icon_car_on_png);
lv_obj_set_width( ui_icon_car_on, LV_SIZE_CONTENT);  /// 58
lv_obj_set_height( ui_icon_car_on, LV_SIZE_CONTENT);   /// 88
lv_obj_set_x( ui_icon_car_on, 161 );
lv_obj_set_y( ui_icon_car_on, 189 );
lv_obj_set_align( ui_icon_car_on, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_car_on, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_car_on, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch_ev = lv_switch_create(ui_Screen2);
lv_obj_set_width( ui_Switch_ev, 187);
lv_obj_set_height( ui_Switch_ev, 184);
lv_obj_set_x( ui_Switch_ev, 112 );
lv_obj_set_y( ui_Switch_ev, 157 );
lv_obj_set_align( ui_Switch_ev, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Switch_ev, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_ev, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_ev, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch_ev, 0, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_Switch_ev, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_ev, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_ev, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch_ev, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_Switch_ev, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_ev, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_ev, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch_ev, 0, LV_PART_KNOB| LV_STATE_CHECKED);

lv_obj_add_event_cb(ui_Slider_vacuum_batt, ui_event_Slider_vacuum_batt, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch_vacuum, ui_event_Switch_vacuum, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button_Smart, ui_event_Button_Smart, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button_Quick, ui_event_Button_Quick, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button_Linen, ui_event_Button_Linen, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button_Saver, ui_event_Button_Saver, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch_SP, ui_event_Switch_SP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch_ev, ui_event_Switch_ev, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
