// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x212A31), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_Panels = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_Panels);
lv_obj_set_width( ui_Container_Panels, 450);
lv_obj_set_height( ui_Container_Panels, 600);
lv_obj_set_align( ui_Container_Panels, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container_Panels,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_Panels, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container_Panels, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_Panels, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_Panels, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Container_Panels);
lv_obj_set_width( ui_Panel1, 410);
lv_obj_set_height( ui_Panel1, 260);
lv_obj_set_x( ui_Panel1, -39 );
lv_obj_set_y( ui_Panel1, -167 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x8CC0CD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_Panel1);
lv_obj_set_width( ui_Panel11, 300);
lv_obj_set_height( ui_Panel11, 300);
lv_obj_set_x( ui_Panel11, 103 );
lv_obj_set_y( ui_Panel11, -65 );
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel11, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Container_Panels);
lv_obj_set_width( ui_Panel2, 199);
lv_obj_set_height( ui_Panel2, 261);
lv_obj_set_x( ui_Panel2, -39 );
lv_obj_set_y( ui_Panel2, -167 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFECAE1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel14 = lv_obj_create(ui_Panel2);
lv_obj_set_width( ui_Panel14, 200);
lv_obj_set_height( ui_Panel14, 200);
lv_obj_set_x( ui_Panel14, 97 );
lv_obj_set_y( ui_Panel14, -2 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel14, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Container_Panels);
lv_obj_set_width( ui_Panel3, 199);
lv_obj_set_height( ui_Panel3, 261);
lv_obj_set_x( ui_Panel3, -39 );
lv_obj_set_y( ui_Panel3, -167 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x90E6B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel15 = lv_obj_create(ui_Panel3);
lv_obj_set_width( ui_Panel15, 200);
lv_obj_set_height( ui_Panel15, 200);
lv_obj_set_x( ui_Panel15, 93 );
lv_obj_set_y( ui_Panel15, -4 );
lv_obj_set_align( ui_Panel15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel15, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Icon_tv = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Icon_tv, &ui_img_img_icon_tv_png);
lv_obj_set_width( ui_Icon_tv, LV_SIZE_CONTENT);  /// 220
lv_obj_set_height( ui_Icon_tv, LV_SIZE_CONTENT);   /// 184
lv_obj_set_x( ui_Icon_tv, 122 );
lv_obj_set_y( ui_Icon_tv, -198 );
lv_obj_set_align( ui_Icon_tv, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_tv, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_tv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_tv_off = lv_img_create(ui_Screen1);
lv_img_set_src(ui_icon_tv_off, &ui_img_img_icon_tv_off_png);
lv_obj_set_width( ui_icon_tv_off, LV_SIZE_CONTENT);  /// 220
lv_obj_set_height( ui_icon_tv_off, LV_SIZE_CONTENT);   /// 184
lv_obj_set_x( ui_icon_tv_off, 121 );
lv_obj_set_y( ui_icon_tv_off, -198 );
lv_obj_set_align( ui_icon_tv_off, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_tv_off, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_tv_off, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_ac = lv_img_create(ui_Screen1);
lv_img_set_src(ui_icon_ac, &ui_img_img_icon_ac_png);
lv_obj_set_width( ui_icon_ac, LV_SIZE_CONTENT);  /// 162
lv_obj_set_height( ui_icon_ac, LV_SIZE_CONTENT);   /// 103
lv_obj_set_x( ui_icon_ac, -74 );
lv_obj_set_y( ui_icon_ac, 39 );
lv_obj_set_align( ui_icon_ac, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_ac, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_ac, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_ac_on = lv_img_create(ui_icon_ac);
lv_img_set_src(ui_icon_ac_on, &ui_img_img_icon_ac_on_png);
lv_obj_set_width( ui_icon_ac_on, LV_SIZE_CONTENT);  /// 141
lv_obj_set_height( ui_icon_ac_on, LV_SIZE_CONTENT);   /// 77
lv_obj_set_x( ui_icon_ac_on, 23 );
lv_obj_set_y( ui_icon_ac_on, 24 );
lv_obj_set_align( ui_icon_ac_on, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_ac_on, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_ac_on, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_icon_lamp = lv_img_create(ui_Screen1);
lv_img_set_src(ui_icon_lamp, &ui_img_img_icon_lamp1_png);
lv_obj_set_width( ui_icon_lamp, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_icon_lamp, LV_SIZE_CONTENT);   /// 167
lv_obj_set_x( ui_icon_lamp, 172 );
lv_obj_set_y( ui_icon_lamp, 74 );
lv_obj_set_align( ui_icon_lamp, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_lamp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_lamp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_lamp_on = lv_img_create(ui_icon_lamp);
lv_img_set_src(ui_Icon_lamp_on, &ui_img_img_icon_lamp_on_png);
lv_obj_set_width( ui_Icon_lamp_on, LV_SIZE_CONTENT);  /// 90
lv_obj_set_height( ui_Icon_lamp_on, LV_SIZE_CONTENT);   /// 30
lv_obj_set_x( ui_Icon_lamp_on, -1 );
lv_obj_set_y( ui_Icon_lamp_on, 49 );
lv_obj_set_align( ui_Icon_lamp_on, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_lamp_on, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_lamp_on, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_LR = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_LR);
lv_obj_set_width( ui_Container_LR, 410);
lv_obj_set_height( ui_Container_LR, 260);
lv_obj_set_x( ui_Container_LR, 0 );
lv_obj_set_y( ui_Container_LR, -137 );
lv_obj_set_align( ui_Container_LR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_LR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Living_Room = lv_label_create(ui_Container_LR);
lv_obj_set_width( ui_Label_Living_Room, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Living_Room, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Living_Room, 15 );
lv_obj_set_y( ui_Label_Living_Room, 28 );
lv_label_set_text(ui_Label_Living_Room,"Living Room");
lv_obj_set_style_text_color(ui_Label_Living_Room, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Living_Room, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Living_Room, &ui_font_Kanit35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_TV = lv_label_create(ui_Container_LR);
lv_obj_set_width( ui_Label_TV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_TV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_TV, 104 );
lv_obj_set_y( ui_Label_TV, 181 );
lv_label_set_text(ui_Label_TV,"TV");
lv_obj_set_style_text_color(ui_Label_TV, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_TV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_TV, &ui_font_Kanit35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_TV_Stat = lv_label_create(ui_Container_LR);
lv_obj_set_width( ui_Label_TV_Stat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_TV_Stat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_TV_Stat, 104 );
lv_obj_set_y( ui_Label_TV_Stat, 215 );
lv_label_set_text(ui_Label_TV_Stat,"OFF");
lv_obj_set_style_text_color(ui_Label_TV_Stat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_TV_Stat, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_TV_Stat, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch_TV = lv_switch_create(ui_Container_LR);
lv_obj_set_width( ui_Switch_TV, 80);
lv_obj_set_height( ui_Switch_TV, 80);
lv_obj_set_x( ui_Switch_TV, -152 );
lv_obj_set_y( ui_Switch_TV, 78 );
lv_obj_set_align( ui_Switch_TV, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Switch_TV, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_TV, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_TV, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Switch_TV, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_TV, lv_color_hex(0xACAEAC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_TV, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch_TV, lv_color_hex(0x31BE08), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch_TV, 100, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_Switch_TV, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch_TV, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch_TV, &ui_img_636281941, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_recolor(ui_Switch_TV, lv_color_hex(0xAFAFAF), LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_Switch_TV, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Switch_TV, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Switch_TV, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Switch_TV, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Switch_TV, -5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch_TV, &ui_img_636281941, LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_img_recolor(ui_Switch_TV, lv_color_hex(0x35BD0C), LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_recolor_opa(ui_Switch_TV, 255, LV_PART_KNOB| LV_STATE_CHECKED);

ui_Container4 = lv_obj_create(ui_Container_LR);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 185);
lv_obj_set_height( ui_Container4, 50);
lv_obj_set_x( ui_Container4, -99 );
lv_obj_set_y( ui_Container4, -19 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_time = lv_label_create(ui_Container4);
lv_obj_set_height( ui_Label_time, 40);
lv_obj_set_width( ui_Label_time, LV_SIZE_CONTENT);  /// 56
lv_obj_set_x( ui_Label_time, -7 );
lv_obj_set_y( ui_Label_time, 0 );
lv_label_set_text(ui_Label_time,"10:10");
lv_obj_set_style_text_color(ui_Label_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_time, &ui_font_Kanit60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_amPm = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label_amPm, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_Label_amPm, LV_SIZE_CONTENT);   /// 40
lv_label_set_text(ui_Label_amPm,"AM");
lv_obj_set_style_text_color(ui_Label_amPm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_amPm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_amPm, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_pagination = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_pagination);
lv_obj_set_width( ui_Container_pagination, 200);
lv_obj_set_height( ui_Container_pagination, 23);
lv_obj_set_x( ui_Container_pagination, 0 );
lv_obj_set_y( ui_Container_pagination, -10 );
lv_obj_set_align( ui_Container_pagination, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Container_pagination,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_pagination, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Container_pagination, LV_OBJ_FLAG_FLOATING );   /// Flags
lv_obj_clear_flag( ui_Container_pagination, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_pagination, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_pagination, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_Container_pagination);
lv_obj_set_width( ui_Panel8, 10);
lv_obj_set_height( ui_Panel8, 10);
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_Container_pagination);
lv_obj_set_width( ui_Panel9, 10);
lv_obj_set_height( ui_Panel9, 10);
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_AC = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_AC);
lv_obj_set_width( ui_Container_AC, 204);
lv_obj_set_height( ui_Container_AC, 262);
lv_obj_set_x( ui_Container_AC, -107 );
lv_obj_set_y( ui_Container_AC, 137 );
lv_obj_set_align( ui_Container_AC, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_AC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Slider_AC = lv_slider_create(ui_Container_AC);
lv_slider_set_range(ui_Slider_AC, 15,25);
lv_slider_set_value( ui_Slider_AC, 15, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_AC)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_AC, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_AC, 69);
lv_obj_set_height( ui_Slider_AC, 174);
lv_obj_set_x( ui_Slider_AC, -57 );
lv_obj_set_y( ui_Slider_AC, 7 );
lv_obj_set_align( ui_Slider_AC, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Slider_AC, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_AC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_AC, 40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_AC, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_AC, lv_color_hex(0xF069B0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_AC, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_AC, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_AC, lv_color_hex(0xFFEBF6), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_AC, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Slider_AC, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Slider_AC, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Slider_AC, -30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Slider_AC, -30, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Container_AC);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 97);
lv_obj_set_height( ui_Container2, 50);
lv_obj_set_x( ui_Container2, 45 );
lv_obj_set_y( ui_Container2, 81 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_temp = lv_label_create(ui_Container2);
lv_obj_set_height( ui_Label_temp, 40);
lv_obj_set_width( ui_Label_temp, LV_SIZE_CONTENT);  /// 56
lv_label_set_text(ui_Label_temp,"15");
lv_obj_set_style_text_color(ui_Label_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_temp, &ui_font_Kanit50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item2 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label_item2, 32);
lv_obj_set_height( ui_Label_item2, 40);
lv_label_set_text(ui_Label_item2,"°C");
lv_obj_set_style_text_color(ui_Label_item2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item2, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_AC = lv_label_create(ui_Container_AC);
lv_obj_set_width( ui_Label_AC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_AC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_AC, 100 );
lv_obj_set_y( ui_Label_AC, 130 );
lv_label_set_text(ui_Label_AC,"AC");
lv_obj_set_style_text_color(ui_Label_AC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_AC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_AC, &ui_font_Kanit35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_ac_set = lv_label_create(ui_Container_AC);
lv_obj_set_width( ui_Label_ac_set, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_ac_set, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_ac_set, 101 );
lv_obj_set_y( ui_Label_ac_set, 158 );
lv_label_set_text(ui_Label_ac_set,"Set ");
lv_obj_set_style_text_color(ui_Label_ac_set, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_ac_set, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_ac_set, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_lamp = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_lamp);
lv_obj_set_width( ui_Container_lamp, 196);
lv_obj_set_height( ui_Container_lamp, 260);
lv_obj_set_x( ui_Container_lamp, 107 );
lv_obj_set_y( ui_Container_lamp, 138 );
lv_obj_set_align( ui_Container_lamp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_lamp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Slider_Lamp = lv_slider_create(ui_Container_lamp);
lv_slider_set_range(ui_Slider_Lamp, 0,200);
lv_slider_set_value( ui_Slider_Lamp, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider_Lamp)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider_Lamp, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider_Lamp, 69);
lv_obj_set_height( ui_Slider_Lamp, 174);
lv_obj_set_x( ui_Slider_Lamp, -57 );
lv_obj_set_y( ui_Slider_Lamp, 7 );
lv_obj_set_align( ui_Slider_Lamp, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Slider_Lamp, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Lamp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Lamp, 40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_Lamp, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Lamp, lv_color_hex(0x28A567), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Lamp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Slider_Lamp, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Slider_Lamp, lv_color_hex(0xC4FFE1), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider_Lamp, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Slider_Lamp, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Slider_Lamp, -10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Slider_Lamp, -30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Slider_Lamp, -30, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container_lamp);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 116);
lv_obj_set_height( ui_Container3, 50);
lv_obj_set_x( ui_Container3, 38 );
lv_obj_set_y( ui_Container3, 81 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_lux = lv_label_create(ui_Container3);
lv_obj_set_height( ui_Label_lux, 40);
lv_obj_set_width( ui_Label_lux, LV_SIZE_CONTENT);  /// 56
lv_obj_set_x( ui_Label_lux, -7 );
lv_obj_set_y( ui_Label_lux, 0 );
lv_label_set_text(ui_Label_lux,"0");
lv_obj_set_style_text_color(ui_Label_lux, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_lux, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_lux, &ui_font_Kanit50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item5 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_Label_item5, LV_SIZE_CONTENT);  /// 39
lv_obj_set_height( ui_Label_item5, LV_SIZE_CONTENT);   /// 40
lv_label_set_text(ui_Label_item5,"lx");
lv_obj_set_style_text_color(ui_Label_item5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item5, &ui_font_Kanit25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_item6 = lv_label_create(ui_Container_lamp);
lv_obj_set_width( ui_Label_item6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_item6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_item6, 81 );
lv_obj_set_y( ui_Label_item6, 153 );
lv_label_set_text(ui_Label_item6,"Lamp");
lv_obj_set_style_text_color(ui_Label_item6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_item6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_item6, &ui_font_Kanit35, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Switch_TV, ui_event_Switch_TV, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Slider_AC, ui_event_Slider_AC, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Slider_Lamp, ui_event_Slider_Lamp, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
