// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Stock api

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen
void ui_Screen_screen_init(void);
lv_obj_t *ui_Screen;
lv_obj_t *ui_Panel_main;
lv_obj_t *ui_Image_mask;
lv_obj_t *ui_Panel_Status;
lv_obj_t *ui_symbol_bg;
lv_obj_t *ui_Label_Symbol;
lv_obj_t *ui_Label_date;
lv_obj_t *ui_Container_close;
lv_obj_t *ui_Label_close;
lv_obj_t *ui_Container_rate;
lv_obj_t *ui_icon_open;
lv_obj_t *ui_Label_open;
lv_obj_t *ui_icon_high;
lv_obj_t *ui_Label_high;
lv_obj_t *ui_icon_low;
lv_obj_t *ui_Label_low;
lv_obj_t *ui_Label_volume;
lv_obj_t *ui_icon_volume;
lv_obj_t *ui_Label_updated;
lv_obj_t *ui_icon_timer;
lv_obj_t *ui_Container_Chart;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen);
}
