// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#include "../ui.h"


// COMPONENT widget

lv_obj_t *ui_widget_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_widget;
cui_widget = lv_obj_create(comp_parent);
lv_obj_set_width( cui_widget, 200);
lv_obj_set_height( cui_widget, 200);
lv_obj_set_x( cui_widget, 15 );
lv_obj_set_y( cui_widget, -74 );
lv_obj_set_align( cui_widget, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_widget, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(cui_widget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_wid_bg);
ui_object_set_themeable_style_property(cui_widget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_wid_bg);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_WIDGET_NUM);
children[UI_COMP_WIDGET_WIDGET] = cui_widget;
lv_obj_add_event_cb(cui_widget, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_widget, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_widget_create_hook(cui_widget);
return cui_widget; 
}

