// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#ifndef _UI_COMP_WIDGET_H
#define _UI_COMP_WIDGET_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT widget
#define UI_COMP_WIDGET_WIDGET 0
#define _UI_COMP_WIDGET_NUM 1
lv_obj_t *ui_widget_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
