// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#ifndef _T4_TEST_UI_H
#define _T4_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container_Panels;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Icon_tv;
extern lv_obj_t *ui_icon_tv_off;
extern lv_obj_t *ui_icon_ac;
extern lv_obj_t *ui_icon_ac_on;
extern lv_obj_t *ui_icon_lamp;
extern lv_obj_t *ui_Icon_lamp_on;
extern lv_obj_t *ui_Container_LR;
extern lv_obj_t *ui_Label_Living_Room;
extern lv_obj_t *ui_Label_TV;
extern lv_obj_t *ui_Label_TV_Stat;
void ui_event_Switch_TV( lv_event_t * e);
extern lv_obj_t *ui_Switch_TV;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Label_time;
extern lv_obj_t *ui_Label_amPm;
extern lv_obj_t *ui_Container_pagination;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Container_AC;
void ui_event_Slider_AC( lv_event_t * e);
extern lv_obj_t *ui_Slider_AC;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label_temp;
extern lv_obj_t *ui_Label_item2;
extern lv_obj_t *ui_Label_AC;
extern lv_obj_t *ui_Label_ac_set;
extern lv_obj_t *ui_Container_lamp;
void ui_event_Slider_Lamp( lv_event_t * e);
extern lv_obj_t *ui_Slider_Lamp;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label_lux;
extern lv_obj_t *ui_Label_item5;
extern lv_obj_t *ui_Label_item6;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Container_Panels_1;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel17;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Panel18;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_icon_washing;
extern lv_obj_t *ui_Icon_washing_off;
extern lv_obj_t *ui_icon_cleaner;
extern lv_obj_t *ui_Icon_cleaner_off;
extern lv_obj_t *ui_Container_pagination_1;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Container_cleaner;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Label_batt;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label_battery;
extern lv_obj_t *ui_Label_item8;
void ui_event_Slider_vacuum_batt( lv_event_t * e);
extern lv_obj_t *ui_Slider_vacuum_batt;
extern lv_obj_t *ui_Label_Vacuum;
void ui_event_Switch_vacuum( lv_event_t * e);
extern lv_obj_t *ui_Switch_vacuum;
extern lv_obj_t *ui_Container_WM;
extern lv_obj_t *ui_Container6;
void ui_event_Button_Smart( lv_event_t * e);
extern lv_obj_t *ui_Button_Smart;
extern lv_obj_t *ui_Label_WM1;
void ui_event_Button_Quick( lv_event_t * e);
extern lv_obj_t *ui_Button_Quick;
extern lv_obj_t *ui_Label_WM2;
void ui_event_Button_Linen( lv_event_t * e);
extern lv_obj_t *ui_Button_Linen;
extern lv_obj_t *ui_Label_WM3;
void ui_event_Button_Saver( lv_event_t * e);
extern lv_obj_t *ui_Button_Saver;
extern lv_obj_t *ui_Label_WM4;
extern lv_obj_t *ui_Label_wm_timer;
extern lv_obj_t *ui_Label_wm;
extern lv_obj_t *ui_Container_SP;
void ui_event_Switch_SP( lv_event_t * e);
extern lv_obj_t *ui_Switch_SP;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Label_watt;
extern lv_obj_t *ui_Label_item11;
extern lv_obj_t *ui_Label_item10;
extern lv_obj_t *ui_Label_SP;
extern lv_obj_t *ui_Container_EV;
extern lv_obj_t *ui_Bar_ev;
extern lv_obj_t *ui_Panel19;
extern lv_obj_t *ui_Label_EV;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Label_ev_battery;
extern lv_obj_t *ui_Label_item12;
extern lv_obj_t *ui_icon_smart_plug;
extern lv_obj_t *ui_icon_smart_plug_on;
extern lv_obj_t *ui_icon_car;
extern lv_obj_t *ui_icon_car_on;
void ui_event_Switch_ev( lv_event_t * e);
extern lv_obj_t *ui_Switch_ev;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_img_icon_tv_png);   // assets/img/icon tv.png
LV_IMG_DECLARE( ui_img_img_icon_tv_off_png);   // assets/img/icon tv off.png
LV_IMG_DECLARE( ui_img_img_icon_ac_png);   // assets/img/icon ac.png
LV_IMG_DECLARE( ui_img_img_icon_ac_on_png);   // assets/img/icon ac on.png
LV_IMG_DECLARE( ui_img_img_icon_lamp1_png);   // assets/img/icon lamp1.png
LV_IMG_DECLARE( ui_img_img_icon_lamp_on_png);   // assets/img/icon lamp on.png
LV_IMG_DECLARE( ui_img_636281941);   // assets/img/power-svgrepo-com.png
LV_IMG_DECLARE( ui_img_img_icon_washer_png);   // assets/img/icon washer.png
LV_IMG_DECLARE( ui_img_img_icon_washer_off_png);   // assets/img/icon washer off.png
LV_IMG_DECLARE( ui_img_img_icon_cleaner_png);   // assets/img/icon cleaner.png
LV_IMG_DECLARE( ui_img_img_icon_cleaner_off_png);   // assets/img/icon cleaner off.png
LV_IMG_DECLARE( ui_img_img_icon_plug_png);   // assets/img/icon plug.png
LV_IMG_DECLARE( ui_img_img_icon_plug_on_png);   // assets/img/icon plug on.png
LV_IMG_DECLARE( ui_img_img_icon_car_png);   // assets/img/icon car.png
LV_IMG_DECLARE( ui_img_img_icon_car_on_png);   // assets/img/icon car on.png
LV_IMG_DECLARE( ui_img_img_icon_car_2_png);   // assets/img/icon car 2.png


LV_FONT_DECLARE( ui_font_Kanit25);
LV_FONT_DECLARE( ui_font_Kanit35);
LV_FONT_DECLARE( ui_font_Kanit50);
LV_FONT_DECLARE( ui_font_Kanit60);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
