// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#include "ui.h"

void washingTimer(lv_event_t * e)
{
	// Your code here
}

void smartPlug(lv_event_t * e)
{
	// Your code here
}

void acSlider(lv_event_t * e)
{
	// Your code here
}

void lampSlider(lv_event_t * e)
{
	// Your code here
}