// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void acSlider(lv_event_t * e);
void lampSlider(lv_event_t * e);
void washingTimer(lv_event_t * e);
void smartPlug(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
