// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: t4 test

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_wid_bg[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_wid_bg[1] = {200};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

