// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Stock api

#include "../ui.h"

void ui_Screen_screen_init(void)
{
ui_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_main = lv_obj_create(ui_Screen);
lv_obj_set_width( ui_Panel_main, 415);
lv_obj_set_height( ui_Panel_main, 277);
lv_obj_set_x( ui_Panel_main, 0 );
lv_obj_set_y( ui_Panel_main, 20 );
lv_obj_set_align( ui_Panel_main, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Panel_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_main, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_main, lv_color_hex(0x83FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_main, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel_main, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_mask = lv_img_create(ui_Panel_main);
lv_img_set_src(ui_Image_mask, &ui_img_images_mask_png);
lv_obj_set_width( ui_Image_mask, LV_SIZE_CONTENT);  /// 80
lv_obj_set_height( ui_Image_mask, LV_SIZE_CONTENT);   /// 79
lv_obj_set_x( ui_Image_mask, 18 );
lv_obj_set_y( ui_Image_mask, -18 );
lv_obj_set_align( ui_Image_mask, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_Image_mask, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_mask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel_Status = lv_obj_create(ui_Panel_main);
lv_obj_set_width( ui_Panel_Status, 50);
lv_obj_set_height( ui_Panel_Status, 103);
lv_obj_set_x( ui_Panel_Status, 181 );
lv_obj_set_y( ui_Panel_Status, -83 );
lv_obj_set_align( ui_Panel_Status, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_Status, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_Status, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_Status, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Status, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_Status, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_Status, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_symbol_bg = lv_obj_create(ui_Panel_main);
lv_obj_set_width( ui_symbol_bg, 322);
lv_obj_set_height( ui_symbol_bg, 66);
lv_obj_set_x( ui_symbol_bg, -32 );
lv_obj_set_y( ui_symbol_bg, -96 );
lv_obj_set_align( ui_symbol_bg, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_symbol_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_symbol_bg, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_symbol_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_symbol_bg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_symbol_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_symbol_bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Symbol = lv_label_create(ui_symbol_bg);
lv_obj_set_width( ui_Label_Symbol, 292);
lv_obj_set_height( ui_Label_Symbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label_Symbol, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Symbol,"Symbol");
lv_obj_set_style_text_align(ui_Label_Symbol, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Symbol, &ui_font_ka55, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_date = lv_label_create(ui_Panel_main);
lv_obj_set_width( ui_Label_date, 245);
lv_obj_set_height( ui_Label_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_date, -66 );
lv_obj_set_y( ui_Label_date, -38 );
lv_obj_set_align( ui_Label_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_date,"00-00-0000");
lv_obj_set_style_text_color(ui_Label_date, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date, &ui_font_ka30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_close = lv_obj_create(ui_Panel_main);
lv_obj_remove_style_all(ui_Container_close);
lv_obj_set_width( ui_Container_close, 385);
lv_obj_set_height( ui_Container_close, 81);
lv_obj_set_x( ui_Container_close, -3 );
lv_obj_set_y( ui_Container_close, 15 );
lv_obj_set_align( ui_Container_close, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container_close,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_close, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container_close, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_close, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_close, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_close = lv_label_create(ui_Container_close);
lv_obj_set_width( ui_Label_close, LV_SIZE_CONTENT);  /// 364
lv_obj_set_height( ui_Label_close, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_close, -10 );
lv_obj_set_y( ui_Label_close, 16 );
lv_obj_set_align( ui_Label_close, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_close,"0000");
lv_obj_set_style_text_color(ui_Label_close, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_close, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_close, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_close, &ui_font_ka90, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_rate = lv_obj_create(ui_Panel_main);
lv_obj_remove_style_all(ui_Container_rate);
lv_obj_set_width( ui_Container_rate, 409);
lv_obj_set_height( ui_Container_rate, 37);
lv_obj_set_x( ui_Container_rate, 0 );
lv_obj_set_y( ui_Container_rate, 78 );
lv_obj_set_align( ui_Container_rate, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container_rate,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_rate, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container_rate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_rate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_rate, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_open = lv_img_create(ui_Container_rate);
lv_img_set_src(ui_icon_open, &ui_img_images_open_png);
lv_obj_set_width( ui_icon_open, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_icon_open, LV_SIZE_CONTENT);   /// 18
lv_obj_set_align( ui_icon_open, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_open, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_open, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_open = lv_label_create(ui_Container_rate);
lv_obj_set_width( ui_Label_open, LV_SIZE_CONTENT);  /// 245
lv_obj_set_height( ui_Label_open, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_open, -64 );
lv_obj_set_y( ui_Label_open, -6 );
lv_obj_set_align( ui_Label_open, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_open,"0000");
lv_obj_set_style_text_color(ui_Label_open, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_open, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_open, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_open, &ui_font_ka30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_high = lv_img_create(ui_Container_rate);
lv_img_set_src(ui_icon_high, &ui_img_images_high_png);
lv_obj_set_width( ui_icon_high, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_icon_high, LV_SIZE_CONTENT);   /// 18
lv_obj_set_align( ui_icon_high, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_high, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_high, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_high = lv_label_create(ui_Container_rate);
lv_obj_set_width( ui_Label_high, LV_SIZE_CONTENT);  /// 245
lv_obj_set_height( ui_Label_high, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_high, -64 );
lv_obj_set_y( ui_Label_high, -6 );
lv_obj_set_align( ui_Label_high, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_high,"0000");
lv_obj_set_style_text_color(ui_Label_high, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_high, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_high, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_high, &ui_font_ka30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_low = lv_img_create(ui_Container_rate);
lv_img_set_src(ui_icon_low, &ui_img_images_low_png);
lv_obj_set_width( ui_icon_low, LV_SIZE_CONTENT);  /// 10
lv_obj_set_height( ui_icon_low, LV_SIZE_CONTENT);   /// 18
lv_obj_set_align( ui_icon_low, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_low, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_low, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_low = lv_label_create(ui_Container_rate);
lv_obj_set_width( ui_Label_low, LV_SIZE_CONTENT);  /// 245
lv_obj_set_height( ui_Label_low, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_low, -64 );
lv_obj_set_y( ui_Label_low, -6 );
lv_obj_set_align( ui_Label_low, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_low,"0000");
lv_obj_set_style_text_color(ui_Label_low, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_low, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_low, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_low, &ui_font_ka30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_volume = lv_label_create(ui_Panel_main);
lv_obj_set_width( ui_Label_volume, 153);
lv_obj_set_height( ui_Label_volume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_volume, -90 );
lv_obj_set_y( ui_Label_volume, 117 );
lv_obj_set_align( ui_Label_volume, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_volume,"00000");
lv_obj_set_style_text_color(ui_Label_volume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_volume, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_volume, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_volume, &ui_font_ka30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_volume = lv_img_create(ui_Panel_main);
lv_img_set_src(ui_icon_volume, &ui_img_images_volume_png);
lv_obj_set_width( ui_icon_volume, LV_SIZE_CONTENT);  /// 18
lv_obj_set_height( ui_icon_volume, LV_SIZE_CONTENT);   /// 18
lv_obj_set_x( ui_icon_volume, -180 );
lv_obj_set_y( ui_icon_volume, 113 );
lv_obj_set_align( ui_icon_volume, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_volume, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_volume, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_updated = lv_label_create(ui_Panel_main);
lv_obj_set_width( ui_Label_updated, 180);
lv_obj_set_height( ui_Label_updated, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_updated, 105 );
lv_obj_set_y( ui_Label_updated, 117 );
lv_obj_set_align( ui_Label_updated, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_updated,"00000");
lv_obj_set_style_text_color(ui_Label_updated, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_updated, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_updated, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_updated, &ui_font_ka30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_icon_timer = lv_img_create(ui_Panel_main);
lv_img_set_src(ui_icon_timer, &ui_img_images_timer_png);
lv_obj_set_width( ui_icon_timer, LV_SIZE_CONTENT);  /// 18
lv_obj_set_height( ui_icon_timer, LV_SIZE_CONTENT);   /// 18
lv_obj_set_x( ui_icon_timer, 0 );
lv_obj_set_y( ui_icon_timer, 115 );
lv_obj_set_align( ui_icon_timer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_icon_timer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_icon_timer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container_Chart = lv_obj_create(ui_Screen);
lv_obj_remove_style_all(ui_Container_Chart);
lv_obj_set_width( ui_Container_Chart, 410);
lv_obj_set_height( ui_Container_Chart, 210);
lv_obj_set_x( ui_Container_Chart, 0 );
lv_obj_set_y( ui_Container_Chart, -15 );
lv_obj_set_align( ui_Container_Chart, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Container_Chart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags


}
